from __future__ import annotations

import ast
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "chronorisk"
TESTS = ROOT / "tests"

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "placeholder",
    "comprehensive",
    "state-of-the-art",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
)


def _python_files(*roots: Path) -> list[Path]:
    found: list[Path] = []
    for root in roots:
        found.extend(sorted(root.rglob("*.py")))
    return found


def test_sources_have_no_comments() -> None:
    for path in _python_files(PACKAGE, TESTS):
        with path.open("rb") as handle:
            tokens = tokenize.tokenize(handle.readline)
            comments = [tok for tok in tokens if tok.type == tokenize.COMMENT]
        assert comments == [], f"comment found in {path.name}"


def test_sources_have_no_docstrings() -> None:
    for path in _python_files(PACKAGE, TESTS):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                assert ast.get_docstring(node) is None, f"docstring in {path.name}"


def test_no_forbidden_phrases() -> None:
    targets = _python_files(PACKAGE)
    targets += [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        text = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN:
            assert phrase not in text, f"forbidden phrase '{phrase}' in {path.name}"


def test_no_emoji() -> None:
    targets = _python_files(PACKAGE)
    targets += [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        for character in path.read_text(encoding="utf-8"):
            point = ord(character)
            assert not (0x2600 <= point <= 0x27BF), f"emoji in {path.name}"
            assert not (0x1F000 <= point <= 0x1FAFF), f"emoji in {path.name}"
